import sys
import json
import sqlite3
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = Path(r"C:\Users\USER\Desktop\3")
PROJ_MAP_FILE = BASE_DIR / "projects_map.json"
DB_FILE = BASE_DIR / "nexa_database.db"

# Complete Intelligence & Metadata for all 22 CB VIP Projects
PROJECTS_INTELLIGENCE = [
    {
        "id": "cbvip-prj-1",
        "db_id": 1,
        "title": "ANGİM BEYTEPE",
        "name": "ANGİM BEYTEPE",
        "folder_name": "02_ANGIM_BEYTEPE",
        "location": "Beytepe / Çankaya",
        "developer": "Angim Yapı & CB VIP",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_1.jpg",
        "image": "/static/img/video_thumbs/video_thumb_1.jpg",
        "cloud_direct_url": "https://files.catbox.moe/adtx6s.mp4",
        "tanitim_cloud_url": "https://files.catbox.moe/adtx6s.mp4",
        "slideshow_cloud_url": "https://files.catbox.moe/adtx6s.mp4",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - ANGİM BEYTEPE.pdf", "path": "projeler/02_ANGIM_BEYTEPE/SUNUM - ANGİM BEYTEPE.pdf"}],
        "media": {
            "promo_video_url": "https://files.catbox.moe/adtx6s.mp4",
            "slideshow_video_url": "https://files.catbox.moe/adtx6s.mp4",
            "pdf_url": "/projeler/02_ANGIM_BEYTEPE/SUNUM - ANGİM BEYTEPE.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_1.jpg"
        },
        "intelligence": {
            "region": "Beytepe",
            "price": 4500000,
            "price_display": "4.500.000 TL",
            "price_per_sqm": 38500,
            "region_average": 43800,
            "price_diff_percent": -12,
            "investment_score": 94,
            "pricing_score": "Bölge Ortalamasının %12 Altında (Aşırı Avantajlı)",
            "suitable_for": ["oturum", "yatirim", "uzun_vade"],
            "pros": ["Beytepe bulvarı lokasyonu", "m² fiyat avantajı", "Prestij mimari"],
            "comparison_note": "Beytepe bölgesinde m² başı ortalama fiyat 43.800 TL iken bu proje 38.500 TL ile %12 prim avantajı sunuyor."
        }
    },
    {
        "id": "cbvip-prj-2",
        "db_id": 2,
        "title": "ANKAPORT - SARAY",
        "name": "ANKAPORT - SARAY",
        "folder_name": "03_ANKAPORT_SARAY",
        "location": "Saray / Pursaklar",
        "developer": "Ankaport & CB VIP",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_2.jpg",
        "image": "/static/img/video_thumbs/video_thumb_2.jpg",
        "cloud_direct_url": "https://files.catbox.moe/ycb666.mp4",
        "tanitim_cloud_url": "https://files.catbox.moe/ycb666.mp4",
        "slideshow_cloud_url": "https://files.catbox.moe/ycb666.mp4",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - ANKAPORT SARAY.pdf", "path": "projeler/03_ANKAPORT_SARAY/SUNUM - ANKAPORT SARAY.pdf"}],
        "media": {
            "promo_video_url": "https://files.catbox.moe/ycb666.mp4",
            "slideshow_video_url": "https://files.catbox.moe/ycb666.mp4",
            "pdf_url": "/projeler/03_ANKAPORT_SARAY/SUNUM - ANKAPORT SARAY.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_2.jpg"
        },
        "intelligence": {
            "region": "Saray",
            "price": 3200000,
            "price_display": "3.200.000 TL",
            "price_per_sqm": 24500,
            "region_average": 28000,
            "price_diff_percent": -12.5,
            "investment_score": 91,
            "pricing_score": "Bölge Ortalamasının %12.5 Altında (Yüksek Kiralama Getirisi)",
            "suitable_for": ["kiralik", "yatirim", "oturum"],
            "pros": ["Kazan/Saray sanayi ve ulaşım aksı", "Yüksek kira getirisi", "Uyguna giriş fırsatı"],
            "comparison_note": "3M TL bütçede kiralık yatırım için amortisman süresi en kısa seçenektir."
        }
    },
    {
        "id": "cbvip-prj-3",
        "db_id": 3,
        "title": "EVART YALIKAVAK",
        "name": "EVART YALIKAVAK",
        "folder_name": "10_EVART_YALIKAVAK",
        "location": "Yalıkavak / Bodrum",
        "developer": "Evart Gayrimenkul",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_3.jpg",
        "image": "/static/img/video_thumbs/video_thumb_3.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-3",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-3",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-3",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - EVART YALIKAVAK.pdf", "path": "projeler/10_EVART_YALIKAVAK/SUNUM - EVART YALIKAVAK.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-3",
            "slideshow_video_url": "/stream/video/cbvip-prj-3",
            "pdf_url": "/projeler/10_EVART_YALIKAVAK/SUNUM - EVART YALIKAVAK.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_3.jpg"
        },
        "intelligence": {
            "region": "Yalıkavak / Bodrum",
            "price": 14500000,
            "price_display": "14.500.000 TL",
            "price_per_sqm": 95000,
            "region_average": 110000,
            "price_diff_percent": -13.6,
            "investment_score": 97,
            "pricing_score": "Bodrum Lüks Segmentinde %13.6 Fiyat Avantajı",
            "suitable_for": ["oturum", "yatirim", "uzun_vade"],
            "pros": ["Yalıkavak marina manzaralı villa", "Döviz bazlı yüksek değerlenme", "Ultra lüks donanım"],
            "comparison_note": "Ege ve Bodrum bölgesindeki lüks villa projeleri arasında değer katsayısı en yüksek projedir."
        }
    },
    {
        "id": "cbvip-prj-4",
        "db_id": 4,
        "title": "GRANDE YAŞAMKENT",
        "name": "GRANDE YAŞAMKENT",
        "folder_name": "04_GRANDE_YASAMKENT",
        "location": "Yaşamkent / Çankaya",
        "developer": "Grande Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_4.jpg",
        "image": "/static/img/video_thumbs/video_thumb_4.jpg",
        "cloud_direct_url": "https://files.catbox.moe/olzjrf.mp4",
        "tanitim_cloud_url": "https://files.catbox.moe/olzjrf.mp4",
        "slideshow_cloud_url": "https://files.catbox.moe/olzjrf.mp4",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - GRANDE YAŞAMKENT.pdf", "path": "projeler/04_GRANDE_YASAMKENT/SUNUM - GRANDE YAŞAMKENT.pdf"}],
        "media": {
            "promo_video_url": "https://files.catbox.moe/olzjrf.mp4",
            "slideshow_video_url": "https://files.catbox.moe/olzjrf.mp4",
            "pdf_url": "/projeler/04_GRANDE_YASAMKENT/SUNUM - GRANDE YAŞAMKENT.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_4.jpg"
        },
        "intelligence": {
            "region": "Yaşamkent",
            "price": 5200000,
            "price_display": "5.200.000 TL",
            "price_per_sqm": 41000,
            "region_average": 45000,
            "price_diff_percent": -8.8,
            "investment_score": 93,
            "pricing_score": "Yaşamkent Ortalamasının %8.8 Altında",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Geniş peyzaj alanları", "Aile oturumuna tam uygunluk", "Metro aktarma hattı"],
            "comparison_note": "Yaşamkent'te hem aile yaşamı hem de yüksek likidite arayanlar için en iyi dengedir."
        }
    },
    {
        "id": "cbvip-prj-5",
        "db_id": 5,
        "title": "GÖKDEMİR İMZA",
        "name": "GÖKDEMİR İMZA",
        "folder_name": "05_GOKDEMIR_IMZA",
        "location": "Çakırlar / Yenimahalle",
        "developer": "Gökdemir İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_5.jpg",
        "image": "/static/img/video_thumbs/video_thumb_5.jpg",
        "cloud_direct_url": "https://files.catbox.moe/6qycfr.mp4",
        "tanitim_cloud_url": "https://files.catbox.moe/6qycfr.mp4",
        "slideshow_cloud_url": "https://files.catbox.moe/6qycfr.mp4",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - GÖKDEMİR İMZA.pdf", "path": "projeler/05_GOKDEMIR_IMZA/SUNUM - GÖKDEMİR İMZA.pdf"}],
        "media": {
            "promo_video_url": "https://files.catbox.moe/6qycfr.mp4",
            "slideshow_video_url": "https://files.catbox.moe/6qycfr.mp4",
            "pdf_url": "/projeler/05_GOKDEMIR_IMZA/SUNUM - GÖKDEMİR İMZA.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_5.jpg"
        },
        "intelligence": {
            "region": "Çakırlar / Yenimahalle",
            "price": 3900000,
            "price_display": "3.900.000 TL",
            "price_per_sqm": 31000,
            "region_average": 34500,
            "price_diff_percent": -10.1,
            "investment_score": 89,
            "pricing_score": "Çakırlar Bölgesinde %10 Fiyat Avantajı",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Avm ve metro yakınlığı", "Modern konut kompleksi", "Oturuma hazır teslim"],
            "comparison_note": "4 milyon TL altındaki en dengeli aile oturum ve kiralama seçeneğidir."
        }
    },
    {
        "id": "cbvip-prj-6",
        "db_id": 6,
        "title": "IDEA - START BRAVO",
        "name": "IDEA - START BRAVO",
        "folder_name": "15_IDEA_START_BRAVO",
        "location": "Bağlıca / Etimesgut",
        "developer": "Start Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_6.jpg",
        "image": "/static/img/video_thumbs/video_thumb_6.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-6",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-6",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-6",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - IDEA START BRAVO.pdf", "path": "projeler/15_IDEA_START_BRAVO/SUNUM - IDEA START BRAVO.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-6",
            "slideshow_video_url": "/stream/video/cbvip-prj-6",
            "pdf_url": "/projeler/15_IDEA_START_BRAVO/SUNUM - IDEA START BRAVO.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_6.jpg"
        },
        "intelligence": {
            "region": "Bağlıca",
            "price": 4100000,
            "price_display": "4.100.000 TL",
            "price_per_sqm": 34000,
            "region_average": 37500,
            "price_diff_percent": -9.3,
            "investment_score": 90,
            "pricing_score": "Bölge Ortalamasının %9.3 Altında",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Üniversitelere ve bulvara yakınlık", "Akıllı ev sistemleri"],
            "comparison_note": "Bağlıca bulvar aksında yatırım katsayısı yüksek proje."
        }
    },
    {
        "id": "cbvip-prj-7",
        "db_id": 7,
        "title": "MONZA EYLÜL CONCEPT",
        "name": "MONZA EYLÜL CONCEPT",
        "folder_name": "06_MONZA_EYLUL_CONCEPT",
        "location": "Çakırlar / Yenimahalle",
        "developer": "Monza İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_7.jpg",
        "image": "/static/img/video_thumbs/video_thumb_7.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-7",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-7",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-7",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - MONZA EYLÜL CONCEPT.pdf", "path": "projeler/06_MONZA_EYLUL_CONCEPT/SUNUM - MONZA EYLÜL CONCEPT.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-7",
            "slideshow_video_url": "/stream/video/cbvip-prj-7",
            "pdf_url": "/projeler/06_MONZA_EYLUL_CONCEPT/SUNUM - MONZA EYLÜL CONCEPT.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_7.jpg"
        },
        "intelligence": {
            "region": "Çakırlar",
            "price": 3700000,
            "price_display": "3.700.000 TL",
            "price_per_sqm": 30000,
            "region_average": 34500,
            "price_diff_percent": -13.0,
            "investment_score": 92,
            "pricing_score": "Bölge Ortalamasının %13 Altında",
            "suitable_for": ["kiralik", "yatirim", "oturum"],
            "pros": ["Çakırlar meydana 3dk", "Aşırı cazip lansman fiyatı"],
            "comparison_note": "Fiyat/performans oranında Çakırlar bölgesindeki bir numaralı tercihtir."
        }
    },
    {
        "id": "cbvip-prj-8",
        "db_id": 8,
        "title": "MONZA MOON",
        "name": "MONZA MOON",
        "folder_name": "07_MONZA_MOON",
        "location": "Çakırlar / Yenimahalle",
        "developer": "Monza İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_8.jpg",
        "image": "/static/img/video_thumbs/video_thumb_8.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-8",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-8",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-8",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - MONZA MOON.pdf", "path": "projeler/07_MONZA_MOON/SUNUM - MONZA MOON.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-8",
            "slideshow_video_url": "/stream/video/cbvip-prj-8",
            "pdf_url": "/projeler/07_MONZA_MOON/SUNUM - MONZA MOON.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_8.jpg"
        },
        "intelligence": {
            "region": "Çakırlar",
            "price": 4200000,
            "price_display": "4.200.000 TL",
            "price_per_sqm": 33000,
            "region_average": 34500,
            "price_diff_percent": -4.3,
            "investment_score": 88,
            "pricing_score": "Bölge Standartlarında Değerinde Fiyatlama",
            "suitable_for": ["oturum", "uzun_vade"],
            "pros": ["Konsept mimari", "Butik site konforu"],
            "comparison_note": "Ayrıcalıklı site konsepti ile uzun vadeli nitelikli oturum projesi."
        }
    },
    {
        "id": "cbvip-prj-9",
        "db_id": 9,
        "title": "NARÇİN RONYA CITY - 1",
        "name": "NARÇİN RONYA CITY - 1",
        "folder_name": "08_NARIN_RONYA_CITY",
        "location": "Eryaman / West",
        "developer": "Narçin Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_9.jpg",
        "image": "/static/img/video_thumbs/video_thumb_9.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-9",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-9",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-9",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - NARİN RONYA CITY.pdf", "path": "projeler/08_NARIN_RONYA_CITY/SUNUM - NARİN RONYA CITY.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-9",
            "slideshow_video_url": "/stream/video/cbvip-prj-9",
            "pdf_url": "/projeler/08_NARIN_RONYA_CITY/SUNUM - NARİN RONYA CITY.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_9.jpg"
        },
        "intelligence": {
            "region": "Eryaman / West",
            "price": 3400000,
            "price_display": "3.400.000 TL",
            "price_per_sqm": 27500,
            "region_average": 31000,
            "price_diff_percent": -11.2,
            "investment_score": 91,
            "pricing_score": "Eryaman West Bölgesinde %11 Fiyat Avantajı",
            "suitable_for": ["kiralik", "yatirim", "oturum"],
            "pros": ["Metro istasyonuna yürüme mesafesi", "Yüksek kira talebi"],
            "comparison_note": "Eryaman bölgesinde hızlı kiralanabilirlik puanı en yüksek portföydür."
        }
    },
    {
        "id": "cbvip-prj-10",
        "db_id": 10,
        "title": "NEVA - START BRAVO",
        "name": "NEVA - START BRAVO",
        "folder_name": "20_NEVA_START_BRAVO",
        "location": "Bağlıca / Etimesgut",
        "developer": "Start Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_10.jpg",
        "image": "/static/img/video_thumbs/video_thumb_10.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-10",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-10",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-10",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - NEVA START BRAVO.pdf", "path": "projeler/20_NEVA_START_BRAVO/SUNUM - NEVA START BRAVO.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-10",
            "slideshow_video_url": "/stream/video/cbvip-prj-10",
            "pdf_url": "/projeler/20_NEVA_START_BRAVO/SUNUM - NEVA START BRAVO.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_10.jpg"
        },
        "intelligence": {
            "region": "Bağlıca",
            "price": 4300000,
            "price_display": "4.300.000 TL",
            "price_per_sqm": 35000,
            "region_average": 38000,
            "price_diff_percent": -7.8,
            "investment_score": 89,
            "pricing_score": "Bölge Ortalamasının %7.8 Altında",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Lüks rezidans altyapısı", "Sosyal tesis zenginliği"],
            "comparison_note": "Bağlıca lokasyonunda nitelikli yaşam alanları arayanlar için ideal."
        }
    },
    {
        "id": "cbvip-prj-11",
        "db_id": 11,
        "title": "S POINT - VIP SARAY",
        "name": "S POINT - VIP SARAY",
        "folder_name": "23_S_POINT_SARAY",
        "location": "Saray / Pursaklar",
        "developer": "S Point & CB VIP",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_11.jpg",
        "image": "/static/img/video_thumbs/video_thumb_11.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-11",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-11",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-11",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - S POINT SARAY.pdf", "path": "projeler/23_S_POINT_SARAY/SUNUM - S POINT SARAY.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-11",
            "slideshow_video_url": "/stream/video/cbvip-prj-11",
            "pdf_url": "/projeler/23_S_POINT_SARAY/SUNUM - S POINT SARAY.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_11.jpg"
        },
        "intelligence": {
            "region": "Saray / Pursaklar",
            "price": 2950000,
            "price_display": "2.950.000 TL",
            "price_per_sqm": 23000,
            "region_average": 27000,
            "price_diff_percent": -14.8,
            "investment_score": 95,
            "pricing_score": "3 Milyon TL Altı En Avantajlı Yatırım Projesi (%14.8 Primli)",
            "suitable_for": ["kiralik", "yatirim", "uzun_vade"],
            "pros": ["3M TL bütçeye tam uygunluk", "Yüksek prim potansiyeli"],
            "comparison_note": "3 Milyon TL bütçeyle alınabilecek yatırım ve kiralama katsayısı en yüksek seçenektir."
        }
    },
    {
        "id": "cbvip-prj-12",
        "db_id": 12,
        "title": "TRIOLE YAŞAM",
        "name": "TRIOLE YAŞAM",
        "folder_name": "09_TRIOLE_YASAM",
        "location": "Yaşamkent / Çankaya",
        "developer": "Triole İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_12.jpg",
        "image": "/static/img/video_thumbs/video_thumb_12.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-12",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-12",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-12",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - TRIOLE YAŞAM.pdf", "path": "projeler/09_TRIOLE_YASAM/SUNUM - TRIOLE YAŞAM.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-12",
            "slideshow_video_url": "/stream/video/cbvip-prj-12",
            "pdf_url": "/projeler/09_TRIOLE_YASAM/SUNUM - TRIOLE YAŞAM.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_12.jpg"
        },
        "intelligence": {
            "region": "Yaşamkent",
            "price": 4900000,
            "price_display": "4.900.000 TL",
            "price_per_sqm": 39500,
            "region_average": 45000,
            "price_diff_percent": -12.2,
            "investment_score": 94,
            "pricing_score": "Yaşamkent Bölgesinde %12.2 Fiyat Avantajı",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["3+1 ve 4+1 geniş daireler", "Nitelikli peyzaj"],
            "comparison_note": "5 milyon TL bütçe sınırı olan oturum ve yatırım odaklı alıcılar için ilk tercihtir."
        }
    },
    {
        "id": "cbvip-prj-13",
        "db_id": 13,
        "title": "NEST İNCEK",
        "name": "NEST İNCEK",
        "folder_name": "18_NEST_INCEK",
        "location": "İncek / Gölbaşı",
        "developer": "Nest Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_13.jpg",
        "image": "/static/img/video_thumbs/video_thumb_13.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-13",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-13",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-13",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - NEST İNCEK.pdf", "path": "projeler/18_NEST_INCEK/SUNUM - NEST İNCEK.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-13",
            "slideshow_video_url": "/stream/video/cbvip-prj-13",
            "pdf_url": "/projeler/18_NEST_INCEK/SUNUM - NEST İNCEK.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_13.jpg"
        },
        "intelligence": {
            "region": "İncek / Gölbaşı",
            "price": 6800000,
            "price_display": "6.800.000 TL",
            "price_per_sqm": 48000,
            "region_average": 54000,
            "price_diff_percent": -11.1,
            "investment_score": 93,
            "pricing_score": "İncek Lokasyonunda %11 Fiyat Avantajı",
            "suitable_for": ["oturum", "uzun_vade", "yatirim"],
            "pros": ["Göl manzaralı teraslar", "Üst düzey güvenlik ve donanım"],
            "comparison_note": "İncek bölgesinde prestijli aile konut yatırımı arayanlara önerilir."
        }
    },
    {
        "id": "cbvip-prj-14",
        "db_id": 14,
        "title": "BORDO YAŞAM",
        "name": "BORDO YAŞAM",
        "folder_name": "11_BORDO_YASAM",
        "location": "Yenikent / Sincan",
        "developer": "Bordo İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_14.jpg",
        "image": "/static/img/video_thumbs/video_thumb_14.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-14",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-14",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-14",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - BORDO YAŞAM.pdf", "path": "projeler/11_BORDO_YASAM/SUNUM - BORDO YAŞAM.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-14",
            "slideshow_video_url": "/stream/video/cbvip-prj-14",
            "pdf_url": "/projeler/11_BORDO_YASAM/SUNUM - BORDO YAŞAM.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_14.jpg"
        },
        "intelligence": {
            "region": "Yenikent",
            "price": 2800000,
            "price_display": "2.800.000 TL",
            "price_per_sqm": 22000,
            "region_average": 25500,
            "price_diff_percent": -13.7,
            "investment_score": 92,
            "pricing_score": "En Düşük Bütçeli Prim ve Kiralama Fırsatı (%13.7 Avantajlı)",
            "suitable_for": ["kiralik", "yatirim", "uzun_vade"],
            "pros": ["Uygun giriş fiyatı", "Yüksek amortisman hızı"],
            "comparison_note": "Düşük sermaye ile gayrimenkul yatırımı yapmak isteyenler için ideal."
        }
    },
    {
        "id": "cbvip-prj-15",
        "db_id": 15,
        "title": "EXCELANCE VADİ",
        "name": "EXCELANCE VADİ",
        "folder_name": "12_EXCELANCE_VADI",
        "location": "Vadi / Yenimahalle",
        "developer": "Excelance Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_15.jpg",
        "image": "/static/img/video_thumbs/video_thumb_15.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-15",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-15",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-15",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - EXCELANCE VADİ.pdf", "path": "projeler/12_EXCELANCE_VADI/SUNUM - EXCELANCE VADİ.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-15",
            "slideshow_video_url": "/stream/video/cbvip-prj-15",
            "pdf_url": "/projeler/12_EXCELANCE_VADI/SUNUM - EXCELANCE VADİ.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_15.jpg"
        },
        "intelligence": {
            "region": "Yenikent 2",
            "price": 3100000,
            "price_display": "3.100.000 TL",
            "price_per_sqm": 24000,
            "region_average": 26500,
            "price_diff_percent": -9.4,
            "investment_score": 90,
            "pricing_score": "Bölge Ortalamasının %9.4 Altında",
            "suitable_for": ["kiralik", "oturum", "yatirim"],
            "pros": ["Cadde üzeri konum", "Hızlı kiralama garantisi"],
            "comparison_note": "Düzenli kira geliri hedefleyen yatırımcılar için güvenli portföy."
        }
    },
    {
        "id": "cbvip-prj-16",
        "db_id": 16,
        "title": "EXCELANCE BEYTEPE",
        "name": "EXCELANCE BEYTEPE",
        "folder_name": "13_EXCELANCE_BEYTEPE",
        "location": "Beytepe / Çankaya",
        "developer": "Excelance Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_16.jpg",
        "image": "/static/img/video_thumbs/video_thumb_16.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-16",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-16",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-16",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - EXCELANCE BEYTEPE.pdf", "path": "projeler/13_EXCELANCE_BEYTEPE/SUNUM - EXCELANCE BEYTEPE.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-16",
            "slideshow_video_url": "/stream/video/cbvip-prj-16",
            "pdf_url": "/projeler/13_EXCELANCE_BEYTEPE/SUNUM - EXCELANCE BEYTEPE.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_16.jpg"
        },
        "intelligence": {
            "region": "Beytepe",
            "price": 8500000,
            "price_display": "8.500.000 TL",
            "price_per_sqm": 58000,
            "region_average": 66000,
            "price_diff_percent": -12.1,
            "investment_score": 96,
            "pricing_score": "Beytepe Lüks Segmentte %12 Fiyat Avantajı",
            "suitable_for": ["oturum", "yatirim", "uzun_vade"],
            "pros": ["Beytepe bulvarı cepheli", "Geniş peyzaj ve akıllı ev"],
            "comparison_note": "Beytepe aksında lüks segment aile oturumu arayanlar için en yüksek puanlı proje."
        }
    },
    {
        "id": "cbvip-prj-17",
        "db_id": 17,
        "title": "GÖKDEMİR STAR",
        "name": "GÖKDEMİR STAR",
        "folder_name": "14_GOKDEMIR_STAR",
        "location": "Yaşamkent / Çankaya",
        "developer": "Gökdemir İnşaat",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_17.jpg",
        "image": "/static/img/video_thumbs/video_thumb_17.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-17",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-17",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-17",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - GÖKDEMİR STAR.pdf", "path": "projeler/14_GOKDEMIR_STAR/SUNUM - GÖKDEMİR STAR.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-17",
            "slideshow_video_url": "/stream/video/cbvip-prj-17",
            "pdf_url": "/projeler/14_GOKDEMIR_STAR/SUNUM - GÖKDEMİR STAR.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_17.jpg"
        },
        "intelligence": {
            "region": "Yaşamkent",
            "price": 5400000,
            "price_display": "5.400.000 TL",
            "price_per_sqm": 42500,
            "region_average": 45000,
            "price_diff_percent": -5.5,
            "investment_score": 91,
            "pricing_score": "Yaşamkent Star Projelerinde %5.5 Prim Avantajı",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Gökdemir inşaat güvencesi", "Eksiksiz sosyal alanlar"],
            "comparison_note": "Yaşamkent merkezinde sağlam inşaat kalitesi ve yüksek likidite."
        }
    },
    {
        "id": "cbvip-prj-18",
        "db_id": 18,
        "title": "JOVEN PORT",
        "name": "JOVEN PORT",
        "folder_name": "16_JOVEN_PORT",
        "location": "Yenikent / Sincan",
        "developer": "Joven Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_18.jpg",
        "image": "/static/img/video_thumbs/video_thumb_18.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-18",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-18",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-18",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - JOVEN PORT.pdf", "path": "projeler/16_JOVEN_PORT/SUNUM - JOVEN PORT.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-18",
            "slideshow_video_url": "/stream/video/cbvip-prj-18",
            "pdf_url": "/projeler/16_JOVEN_PORT/SUNUM - JOVEN PORT.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_18.jpg"
        },
        "intelligence": {
            "region": "Yenikent",
            "price": 2950000,
            "price_display": "2.950.000 TL",
            "price_per_sqm": 23500,
            "region_average": 26000,
            "price_diff_percent": -9.6,
            "investment_score": 89,
            "pricing_score": "3M TL Sınırında Yüksek Kiralama Getirisi",
            "suitable_for": ["kiralik", "yatirim"],
            "pros": ["Uyguna kiralık yatırım", "Sıfır binada hemen teslim"],
            "comparison_note": "Yenikent'te kiracı hazır yatırım arayan alıcılara hitap eder."
        }
    },
    {
        "id": "cbvip-prj-19",
        "db_id": 19,
        "title": "JOVEN KAMPÜS",
        "name": "JOVEN KAMPÜS",
        "folder_name": "17_JOVEN_KAMPUS",
        "location": "Çakırlar / Yenimahalle",
        "developer": "Joven Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_19.jpg",
        "image": "/static/img/video_thumbs/video_thumb_19.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-19",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-19",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-19",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - JOVEN KAMPÜS.pdf", "path": "projeler/17_JOVEN_KAMPUS/SUNUM - JOVEN KAMPÜS.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-19",
            "slideshow_video_url": "/stream/video/cbvip-prj-19",
            "pdf_url": "/projeler/17_JOVEN_KAMPUS/SUNUM - JOVEN KAMPÜS.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_19.jpg"
        },
        "intelligence": {
            "region": "Çakırlar",
            "price": 3800000,
            "price_display": "3.800.000 TL",
            "price_per_sqm": 30500,
            "region_average": 34500,
            "price_diff_percent": -11.5,
            "investment_score": 91,
            "pricing_score": "Çakırlar Bölgesinde %11.5 Fiyat Avantajı",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Kolejler bölgesine yakın", "Geniş balkona sahip konutlar"],
            "comparison_note": "Çakırlar mevkisinde 4M TL bütçe ile alınabilecek en avantajlı konut."
        }
    },
    {
        "id": "cbvip-prj-20",
        "db_id": 20,
        "title": "NATURA GOLF",
        "name": "NATURA GOLF",
        "folder_name": "19_NATURA_GOLF",
        "location": "Üniversite Aksı / Çankaya",
        "developer": "Natura Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_20.jpg",
        "image": "/static/img/video_thumbs/video_thumb_20.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-20",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-20",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-20",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - NATURA GOLF.pdf", "path": "projeler/19_NATURA_GOLF/SUNUM - NATURA GOLF.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-20",
            "slideshow_video_url": "/stream/video/cbvip-prj-20",
            "pdf_url": "/projeler/19_NATURA_GOLF/SUNUM - NATURA GOLF.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_20.jpg"
        },
        "intelligence": {
            "region": "Üniversite Aksı / Eskişehir Yolu",
            "price": 3650000,
            "price_display": "3.650.000 TL",
            "price_per_sqm": 32000,
            "region_average": 36000,
            "price_diff_percent": -11.1,
            "investment_score": 93,
            "pricing_score": "Öğrenci & Akademisyen Kiralama Garantili (%11 Avantajlı)",
            "suitable_for": ["kiralik", "yatirim"],
            "pros": ["Hacettepe ve Bilkent üniversitelerine komşu", "Sürekli kiralama garantisi"],
            "comparison_note": "Öğrenci ve akademisyen kiracı kitlesine hitap ettiği için boş kalma riski sıfırdır."
        }
    },
    {
        "id": "cbvip-prj-21",
        "db_id": 21,
        "title": "SMD TWIN",
        "name": "SMD TWIN",
        "folder_name": "21_SMD_TWIN",
        "location": "Bağlıca / Start",
        "developer": "SMD Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_21.jpg",
        "image": "/static/img/video_thumbs/video_thumb_21.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-21",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-21",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-21",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - SMD TWIN.pdf", "path": "projeler/21_SMD_TWIN/SUNUM - SMD TWIN.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-21",
            "slideshow_video_url": "/stream/video/cbvip-prj-21",
            "pdf_url": "/projeler/21_SMD_TWIN/SUNUM - SMD TWIN.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_21.jpg"
        },
        "intelligence": {
            "region": "Bağlıca / Start",
            "price": 4000000,
            "price_display": "4.000.000 TL",
            "price_per_sqm": 33500,
            "region_average": 37500,
            "price_diff_percent": -10.6,
            "investment_score": 90,
            "pricing_score": "Bölge Ortalamasının %10.6 Altında",
            "suitable_for": ["oturum", "yatirim"],
            "pros": ["Modern mimari tasarım", "Site içi geniş spor tesisleri"],
            "comparison_note": "4M TL tam bütçe aralığında hem oturum hem yatırım arayanlar için ideal."
        }
    },
    {
        "id": "cbvip-prj-22",
        "db_id": 22,
        "title": "SMD PROTOKOL",
        "name": "SMD PROTOKOL",
        "folder_name": "22_SMD_PROTOKOL",
        "location": "Çayyolu / Prime",
        "developer": "SMD Yapı",
        "status": "Teslim Sürecinde",
        "thumbnail": "/static/img/video_thumbs/video_thumb_22.jpg",
        "image": "/static/img/video_thumbs/video_thumb_22.jpg",
        "cloud_direct_url": "/stream/video/cbvip-prj-22",
        "tanitim_cloud_url": "/stream/video/cbvip-prj-22",
        "slideshow_cloud_url": "/stream/video/cbvip-prj-22",
        "has_video": True,
        "has_presentation": True,
        "presentations": [{"filename": "SUNUM - SMD PROTOKOL.pdf", "path": "projeler/22_SMD_PROTOKOL/SUNUM - SMD PROTOKOL.pdf"}],
        "media": {
            "promo_video_url": "/stream/video/cbvip-prj-22",
            "slideshow_video_url": "/stream/video/cbvip-prj-22",
            "pdf_url": "/projeler/22_SMD_PROTOKOL/SUNUM - SMD PROTOKOL.pdf",
            "thumbnail_url": "/static/img/video_thumbs/video_thumb_22.jpg"
        },
        "intelligence": {
            "region": "Çayyolu / Prime",
            "price": 7900000,
            "price_display": "7.900.000 TL",
            "price_per_sqm": 54000,
            "region_average": 62000,
            "price_diff_percent": -12.9,
            "investment_score": 95,
            "pricing_score": "Çayyolu Prime Lokasyonunda %12.9 Prim Fırsatı",
            "suitable_for": ["oturum", "uzun_vade", "yatirim"],
            "pros": ["Prime villa & rezidans stili", "Üst segment malzeme kalitesi"],
            "comparison_note": "Çayyolu aksında yüksek gelir grubuna hitap eden prim odaklı proje."
        }
    }
]

# Write to projects_map.json
with open(PROJ_MAP_FILE, "w", encoding="utf-8") as f:
    json.dump(PROJECTS_INTELLIGENCE, f, ensure_ascii=False, indent=2)

print(f"[SUCCESS] Wrote {len(PROJECTS_INTELLIGENCE)} projects to {PROJ_MAP_FILE}")
